export const CURRENT_ISSUES_REQUEST = "CURRENT_ISSUES_REQUEST";
export const CURRENT_ISSUES_SUCCESS = "CURRENT_ISSUES_SUCCESS";
export const CURRENT_ISSUES_FAIL = "CURRENT_ISSUES_FAIL";

export const ISSUE_CREATE_REQUEST = "ISSUE_CREATE_REQUEST";
export const ISSUE_CREATE_SUCCESS = "ISSUE_CREATE_SUCCESS";
export const ISSUE_CREATE_FAIL = "ISSUE_CREATE_FAIL";

export const ISSUE_UPDATE_REQUEST = "ISSUE_UPDATE_REQUEST";
export const ISSUE_UPDATE_SUCCESS = "ISSUE_UPDATE_SUCCESS";
export const ISSUE_UPDATE_FAIL = "ISSUE_UPDATE_FAIL";

export const ISSUE_DELETE_REQUEST = "ISSUE_DELETE_REQUEST";
export const ISSUE_DELETE_SUCCESS = "ISSUE_DELETE_SUCCESS";
export const ISSUE_DELETE_FAIL = "ISSUE_DELETE_FAIL";
